Horizon.UI/MVC/Controllers/FlightController.cs
using MVC.Controllers.Handler;
using MVC.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
  public class FlightController : Controller
  {
    LogicAPIHandler _lah = LogicAPIHandler.Instance;
    // GET: Flight
    public ActionResult Index()
    {
      IEnumerable<Flight> flights = new List<Flight>();
      var res = _lah.GetResponse("Flight/");

      if (res.IsSuccessStatusCode)
      {
        var f= res.Content.ReadAsStringAsync().Result;
        flights = JsonConvert.DeserializeObject<List<Flight>>(f);
        
      return View(flights);
      }

      return View();
    }

    // GET: Flight/Create
    public ActionResult CreateFlight()
    {
      return View();
    }

    // POST: Flight/Create
    [HttpPost]
    public ActionResult CreateFlight(Flight flight)
    {
      //TODO: CreateFlight(flight);
      var res=_lah.PostResponse<Flight>("Flight/", flight);
      if (res.IsSuccessStatusCode)
      {
        return RedirectToAction("Index");
      }
      return View();
    }

    // GET: Flight/Edit/5
    public ActionResult EditFlight(int id)
    {
      //TODO: GetFlight(id);
      var res = _lah.GetResponse("Flight/" + id.ToString());

      if (res.IsSuccessStatusCode)
      {
        return View(res);
      }
      return View();
    }

    // POST: Flight/Edit/5
    [HttpPost]
    public ActionResult EditFlight(int flightId, Flight flight)
    {
      //Flight flightToUpdate = null; //TODO: GetFlight(id)
      //TODO: Send to FlightAPI

      return RedirectToAction("Index");
    }

    // GET: Flight/Delete/5
    public ActionResult DeleteFlight(int flightId)
    {
      //TODO: DeleteFlight(flightId);

      return View();
    }
  }
}

Horizon.UI/MVC/Controllers/PassengerController.cs
using MVC.Controllers.Handler;
using MVC.Models;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class PassengerController : Controller
    {
        LogicAPIHandler _lah = LogicAPIHandler.Instance;

        // GET: Passenger
        public ActionResult Index()
        {
            IEnumerable<Passenger> passengers = new List<Passenger>();
            HttpResponseMessage res = _lah.GetResponse("Passenger/");

            if (res.IsSuccessStatusCode)
            {
                string p = res.Content.ReadAsStringAsync().Result;
                passengers = JsonConvert.DeserializeObject<List<Passenger>>(p);

                return View(passengers);
            }

            return View();
        }

        // GET: Passenger/Create
        public ActionResult CreatePassenger()
        {
            return View();
        }

        // POST: Passenger/Create
        [HttpPost]
        public ActionResult CreatePassenger(Passenger passenger)
        {
            //TODO: CreatePassenger(passenger);
            HttpResponseMessage res = _lah.PostResponse("Passenger/", passenger);

            if (res.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: Passenger/Edit/5
        public ActionResult EditPassenger(int passengerId)
        {
            //TODO: GetPassenger(passengerId);
            HttpResponseMessage res = _lah.GetResponse("Passenger/");

            if (res.IsSuccessStatusCode)
            {
                return View(res);
            }

            return View();
        }

        // POST: Passenger/Edit/5
        [HttpPost]
        public ActionResult EditPassenger(int passengerId, Passenger passenger)
        {
            //TODO: GetPassenger(passengerId);

            return RedirectToAction("Index");
        }

        // GET: Passenger/Delete/5
        public ActionResult Delete(int passengerId)
        {
            //TODO: GetBooking(passengerId); & and RemoveBooking();

            return View();
        }
    }
}

Horizon.UI/MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Horizon Admin", "Index", "Flight", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Flight")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Flight<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("View Flights", "Index", "Flight")</li>
                            <li>@Html.ActionLink("Create Flight", "CreateFlight", "Flight")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Passenger<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("View Passengers", "Index", "Passenger")</li>
                            <li>@Html.ActionLink("Create Passenger", "CreatePassenger", "Passenger")</li>
                        </ul>
                    </li>
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Horizon</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>